// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-todays-session.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_todays_session_default = defineTool({
  name: "get_todays_session",
  title: "Get today's training session",
  description: "Return the signed-in athlete's planned training session(s) for today, including discipline, name, duration, distance, intensity, and workout details.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabaseForUser(ctx).from("planned_sessions").select(
      "id, date, discipline, session_name, duration_min, distance_km, intensity, workout_details, notes, order_index"
    ).eq("athlete_id", ctx.getUserId()).eq("date", today).order("order_index");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? `Found ${rows.length} session(s) for ${today}:

` + rows.map(
      (s) => `\u2022 ${s.session_name} (${s.discipline}) \u2014 ${s.duration_min ?? "?"} min${s.distance_km ? `, ${s.distance_km} km` : ""}${s.intensity ? `, ${s.intensity}` : ""}${s.workout_details ? `
  ${s.workout_details}` : ""}`
    ).join("\n") : `No planned sessions for ${today}.`;
    return {
      content: [{ type: "text", text }],
      structuredContent: { date: today, sessions: rows }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-sessions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_upcoming_sessions_default = defineTool2({
  name: "list_upcoming_sessions",
  title: "List upcoming training sessions",
  description: "List the signed-in athlete's planned sessions from today through the next N days (default 7, max 60).",
  inputSchema: {
    days: z.number().int().min(1).max(60).optional().describe("How many days ahead to include. Defaults to 7.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const window = days ?? 7;
    const start = /* @__PURE__ */ new Date();
    const end = /* @__PURE__ */ new Date();
    end.setDate(end.getDate() + window);
    const startStr = start.toISOString().slice(0, 10);
    const endStr = end.toISOString().slice(0, 10);
    const { data, error } = await supabaseForUser2(ctx).from("planned_sessions").select("id, date, discipline, session_name, duration_min, distance_km, intensity, order_index").eq("athlete_id", ctx.getUserId()).gte("date", startStr).lte("date", endStr).order("date").order("order_index");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? `${rows.length} session(s) between ${startStr} and ${endStr}:

` + rows.map(
      (s) => `\u2022 ${s.date} \u2014 ${s.session_name} (${s.discipline})${s.duration_min ? `, ${s.duration_min} min` : ""}${s.distance_km ? `, ${s.distance_km} km` : ""}${s.intensity ? `, ${s.intensity}` : ""}`
    ).join("\n") : `No planned sessions between ${startStr} and ${endStr}.`;
    return {
      content: [{ type: "text", text }],
      structuredContent: { start: startStr, end: endStr, sessions: rows }
    };
  }
});

// src/lib/mcp/tools/list-recent-completions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_completions_default = defineTool3({
  name: "list_recent_completions",
  title: "List recent completed sessions",
  description: "List the signed-in athlete's most recently completed training sessions with actuals (duration, distance, HR, RPE).",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("How many recent completions to return (default 10, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const n = limit ?? 10;
    const { data, error } = await supabaseForUser3(ctx).from("completed_sessions").select(
      "id, date, discipline, actual_duration_min, actual_distance_km, avg_hr, max_hr, avg_pace, rpe, soreness, pain_flag, notes"
    ).eq("athlete_id", ctx.getUserId()).order("date", { ascending: false }).limit(n);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? rows.map(
      (s) => `\u2022 ${s.date} \u2014 ${s.discipline}${s.actual_duration_min ? `, ${s.actual_duration_min} min` : ""}${s.actual_distance_km ? `, ${s.actual_distance_km} km` : ""}${s.avg_hr ? `, HR ${s.avg_hr}` : ""}${s.rpe ? `, RPE ${s.rpe}` : ""}${s.pain_flag ? " \u26A0\uFE0F pain flag" : ""}`
    ).join("\n") : "No completed sessions yet.";
    return {
      content: [{ type: "text", text }],
      structuredContent: { completions: rows }
    };
  }
});

// src/lib/mcp/tools/get-training-load.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function tsbBand(tsb) {
  if (tsb > 15) return "very fresh";
  if (tsb > 5) return "fresh";
  if (tsb >= -10) return "neutral";
  if (tsb >= -25) return "fatigued";
  return "high injury risk";
}
var get_training_load_default = defineTool4({
  name: "get_training_load",
  title: "Get current training load (CTL/ATL/TSB)",
  description: "Return the athlete's most recent training-load snapshot: chronic training load (CTL), acute training load (ATL), training stress balance (TSB), and a fatigue band interpretation.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("training_load_daily").select("date, ctl, atl, tsb, trimp").eq("athlete_id", ctx.getUserId()).order("date", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [
          { type: "text", text: "No training-load data yet. Log a few sessions and the daily cron will populate CTL/ATL/TSB." }
        ]
      };
    }
    const band = tsbBand(data.tsb);
    const text = `Training load as of ${data.date}:
\u2022 CTL (fitness): ${data.ctl.toFixed(1)}
\u2022 ATL (fatigue): ${data.atl.toFixed(1)}
\u2022 TSB (form): ${data.tsb.toFixed(1)} \u2014 ${band}
\u2022 Today's TRIMP: ${data.trimp.toFixed(0)}`;
    return { content: [{ type: "text", text }], structuredContent: { ...data, band } };
  }
});

// src/lib/mcp/tools/get-goal-race.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_goal_race_default = defineTool5({
  name: "get_goal_race",
  title: "Get goal race",
  description: "Return the signed-in athlete's current HYROX goal race: name, date, location, target finish time, and days until race day.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("profiles").select("full_name, goal_race_name, goal_race_date, goal_race_location, goal_finish_time_seconds").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.goal_race_date) {
      return { content: [{ type: "text", text: "No goal race set." }] };
    }
    const days = Math.ceil((new Date(data.goal_race_date).getTime() - Date.now()) / 864e5);
    const targetHms = data.goal_finish_time_seconds ? new Date(data.goal_finish_time_seconds * 1e3).toISOString().slice(11, 19) : null;
    const text = `Goal race for ${data.full_name}:
\u2022 ${data.goal_race_name ?? "HYROX"} \u2014 ${data.goal_race_date}${data.goal_race_location ? ` (${data.goal_race_location})` : ""}
\u2022 ${days > 0 ? `${days} days to go` : days === 0 ? "Race day!" : `${-days} days since race`}` + (targetHms ? `
\u2022 Target finish: ${targetHms}` : "");
    return { content: [{ type: "text", text }], structuredContent: { ...data, daysUntil: days } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cdrpypapdqbwwiuqvqti";
var mcp_default = defineMcp({
  name: "hybrid-athletics-mcp",
  title: "Hybrid Athletics",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in HYROX athlete's training data on Hybrid Athletics. Use `get_todays_session` for today's workout, `list_upcoming_sessions` to look ahead, `list_recent_completions` for recent training history, `get_training_load` for the current CTL/ATL/TSB fitness/fatigue snapshot, and `get_goal_race` for the athlete's next HYROX race. All tools return data for the signed-in user only.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_todays_session_default, list_upcoming_sessions_default, list_recent_completions_default, get_training_load_default, get_goal_race_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
