// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-todays-session.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_todays_session_default = defineTool({
  name: "get_todays_session",
  title: "Get today's training session",
  description: "Return the signed-in athlete's planned training session(s) for today, including discipline, name, duration, distance, intensity, and workout details.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabaseForUser(ctx).from("planned_sessions").select(
      "id, date, discipline, session_name, duration_min, distance_km, intensity, workout_details, notes, order_index"
    ).eq("athlete_id", ctx.getUserId()).eq("date", today).order("order_index");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? `Found ${rows.length} session(s) for ${today}:

` + rows.map(
      (s) => `\u2022 ${s.session_name} (${s.discipline}) \u2014 ${s.duration_min ?? "?"} min${s.distance_km ? `, ${s.distance_km} km` : ""}${s.intensity ? `, ${s.intensity}` : ""}${s.workout_details ? `
  ${s.workout_details}` : ""}`
    ).join("\n") : `No planned sessions for ${today}.`;
    return {
      content: [{ type: "text", text }],
      structuredContent: { date: today, sessions: rows }
    };
  }
});

// src/lib/mcp/tools/list-upcoming-sessions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_upcoming_sessions_default = defineTool2({
  name: "list_upcoming_sessions",
  title: "List upcoming training sessions",
  description: "List the signed-in athlete's planned sessions from today through the next N days (default 7, max 60).",
  inputSchema: {
    days: z.number().int().min(1).max(60).optional().describe("How many days ahead to include. Defaults to 7.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const window = days ?? 7;
    const start = /* @__PURE__ */ new Date();
    const end = /* @__PURE__ */ new Date();
    end.setDate(end.getDate() + window);
    const startStr = start.toISOString().slice(0, 10);
    const endStr = end.toISOString().slice(0, 10);
    const { data, error } = await supabaseForUser2(ctx).from("planned_sessions").select("id, date, discipline, session_name, duration_min, distance_km, intensity, order_index").eq("athlete_id", ctx.getUserId()).gte("date", startStr).lte("date", endStr).order("date").order("order_index");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? `${rows.length} session(s) between ${startStr} and ${endStr}:

` + rows.map(
      (s) => `\u2022 ${s.date} \u2014 ${s.session_name} (${s.discipline})${s.duration_min ? `, ${s.duration_min} min` : ""}${s.distance_km ? `, ${s.distance_km} km` : ""}${s.intensity ? `, ${s.intensity}` : ""}`
    ).join("\n") : `No planned sessions between ${startStr} and ${endStr}.`;
    return {
      content: [{ type: "text", text }],
      structuredContent: { start: startStr, end: endStr, sessions: rows }
    };
  }
});

// src/lib/mcp/tools/list-recent-completions.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_completions_default = defineTool3({
  name: "list_recent_completions",
  title: "List recent completed sessions",
  description: "List the signed-in athlete's most recently completed training sessions with actuals (duration, distance, HR, RPE).",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("How many recent completions to return (default 10, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const n = limit ?? 10;
    const { data, error } = await supabaseForUser3(ctx).from("completed_sessions").select(
      "id, date, discipline, actual_duration_min, actual_distance_km, avg_hr, max_hr, avg_pace, rpe, soreness, pain_flag, notes"
    ).eq("athlete_id", ctx.getUserId()).order("date", { ascending: false }).limit(n);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? rows.map(
      (s) => `\u2022 ${s.date} \u2014 ${s.discipline}${s.actual_duration_min ? `, ${s.actual_duration_min} min` : ""}${s.actual_distance_km ? `, ${s.actual_distance_km} km` : ""}${s.avg_hr ? `, HR ${s.avg_hr}` : ""}${s.rpe ? `, RPE ${s.rpe}` : ""}${s.pain_flag ? " \u26A0\uFE0F pain flag" : ""}`
    ).join("\n") : "No completed sessions yet.";
    return {
      content: [{ type: "text", text }],
      structuredContent: { completions: rows }
    };
  }
});

// src/lib/mcp/tools/get-training-load.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function tsbBand(tsb) {
  if (tsb > 15) return "very fresh";
  if (tsb > 5) return "fresh";
  if (tsb >= -10) return "neutral";
  if (tsb >= -25) return "fatigued";
  return "high injury risk";
}
var get_training_load_default = defineTool4({
  name: "get_training_load",
  title: "Get current training load (CTL/ATL/TSB)",
  description: "Return the athlete's most recent training-load snapshot: chronic training load (CTL), acute training load (ATL), training stress balance (TSB), and a fatigue band interpretation.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("training_load_daily").select("date, ctl, atl, tsb, trimp").eq("athlete_id", ctx.getUserId()).order("date", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [
          { type: "text", text: "No training-load data yet. Log a few sessions and the daily cron will populate CTL/ATL/TSB." }
        ]
      };
    }
    const band = tsbBand(data.tsb);
    const text = `Training load as of ${data.date}:
\u2022 CTL (fitness): ${data.ctl.toFixed(1)}
\u2022 ATL (fatigue): ${data.atl.toFixed(1)}
\u2022 TSB (form): ${data.tsb.toFixed(1)} \u2014 ${band}
\u2022 Today's TRIMP: ${data.trimp.toFixed(0)}`;
    return { content: [{ type: "text", text }], structuredContent: { ...data, band } };
  }
});

// src/lib/mcp/tools/get-goal-race.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_goal_race_default = defineTool5({
  name: "get_goal_race",
  title: "Get goal race",
  description: "Return the signed-in athlete's current HYROX goal race: name, date, location, target finish time, and days until race day.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("profiles").select("full_name, goal_race_name, goal_race_date, goal_race_location, goal_finish_time_seconds").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data?.goal_race_date) {
      return { content: [{ type: "text", text: "No goal race set." }] };
    }
    const days = Math.ceil((new Date(data.goal_race_date).getTime() - Date.now()) / 864e5);
    const targetHms = data.goal_finish_time_seconds ? new Date(data.goal_finish_time_seconds * 1e3).toISOString().slice(11, 19) : null;
    const text = `Goal race for ${data.full_name}:
\u2022 ${data.goal_race_name ?? "HYROX"} \u2014 ${data.goal_race_date}${data.goal_race_location ? ` (${data.goal_race_location})` : ""}
\u2022 ${days > 0 ? `${days} days to go` : days === 0 ? "Race day!" : `${-days} days since race`}` + (targetHms ? `
\u2022 Target finish: ${targetHms}` : "");
    return { content: [{ type: "text", text }], structuredContent: { ...data, daysUntil: days } };
  }
});

// src/lib/mcp/tools/list-strava-activities.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.98.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function paceLabel(secPerKm) {
  if (!secPerKm || secPerKm <= 0) return "";
  const m = Math.floor(secPerKm / 60);
  const s = Math.round(secPerKm % 60);
  return ` | ${m}:${String(s).padStart(2, "0")}/km`;
}
var list_strava_activities_default = defineTool6({
  name: "list_strava_activities",
  title: "List synced Strava activities",
  description: "Return the signed-in athlete's Strava activities synced into the app over a recent window, optionally filtered to one discipline (run, bike, rowing, strength, mobility, hyrox_station, custom).",
  inputSchema: {
    days: z3.number().nullable().describe("Size of the look-back window in days (1-180). Defaults to 14."),
    discipline: z3.string().nullable().describe("Optional discipline filter, e.g. run or bike. Null returns every discipline.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const days = Math.min(180, Math.max(1, Math.round(Number(input?.days) || 14)));
    const since = new Date(Date.now() - days * 864e5).toISOString();
    let query = supabaseForUser6(ctx).from("strava_activities").select(
      "start_date_local, sport_type, name, discipline, distance_m, duration_sec, avg_hr, max_hr, avg_pace_min_per_km, completed_session_id"
    ).eq("user_id", ctx.getUserId()).gte("start_date_local", since).order("start_date_local", { ascending: false }).limit(100);
    if (input?.discipline) query = query.eq("discipline", input.discipline);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) {
      return {
        content: [{ type: "text", text: `No synced Strava activities in the last ${days} days.` }]
      };
    }
    const lines = data.map((a) => {
      const date = String(a.start_date_local ?? "").slice(0, 10);
      const km = a.distance_m ? `${(Number(a.distance_m) / 1e3).toFixed(1)}km` : "\u2014";
      const min = a.duration_sec ? `${Math.round(Number(a.duration_sec) / 60)}min` : "\u2014";
      const hr = a.avg_hr ? ` | avg HR ${a.avg_hr}${a.max_hr ? `/max ${a.max_hr}` : ""}` : "";
      const pace = paceLabel(a.avg_pace_min_per_km ? Number(a.avg_pace_min_per_km) * 60 : null);
      const matched = a.completed_session_id ? " | logged" : " | not logged";
      return `- ${date}: ${a.discipline ?? a.sport_type} "${a.name ?? ""}" | ${km} | ${min}${hr}${pace}${matched}`;
    });
    return {
      content: [{ type: "text", text: `Strava activities (last ${days} days):
${lines.join("\n")}` }],
      structuredContent: { days, count: data.length, activities: data }
    };
  }
});

// src/lib/mcp/tools/get-weekly-rollup.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.98.0";
import { z as z4 } from "npm:zod@^3.25.76";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_weekly_rollup_default = defineTool7({
  name: "get_weekly_rollup",
  title: "Get weekly training rollup per discipline",
  description: "Summarise the signed-in athlete's logged training over a trailing number of weeks: sessions, hours, kilometres and average heart rate per discipline, plus hours per week.",
  inputSchema: {
    weeks: z4.number().nullable().describe("Number of trailing weeks to summarise (1-26). Defaults to 4.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const weeks = Math.min(26, Math.max(1, Math.round(Number(input?.weeks) || 4)));
    const since = new Date(Date.now() - weeks * 7 * 864e5).toISOString().slice(0, 10);
    const { data, error } = await supabaseForUser7(ctx).from("completed_sessions").select("date, discipline, actual_duration_min, actual_distance_km, avg_hr, source").eq("athlete_id", ctx.getUserId()).gte("date", since).order("date", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: `No logged sessions in the last ${weeks} weeks.` }] };
    }
    const byDiscipline = /* @__PURE__ */ new Map();
    let totalHours = 0;
    for (const s of data) {
      const key = String(s.discipline ?? "custom");
      const b = byDiscipline.get(key) ?? { sessions: 0, hours: 0, km: 0, hrSum: 0, hrCount: 0 };
      const minutes = Number(s.actual_duration_min ?? 0) || 0;
      b.sessions++;
      b.hours += minutes / 60;
      b.km += Number(s.actual_distance_km ?? 0) || 0;
      if (s.avg_hr) {
        b.hrSum += Number(s.avg_hr);
        b.hrCount++;
      }
      byDiscipline.set(key, b);
      totalHours += minutes / 60;
    }
    const rows = [...byDiscipline.entries()].sort((a, b) => b[1].hours - a[1].hours).map(([discipline, b]) => ({
      discipline,
      sessions: b.sessions,
      hours: Math.round(b.hours * 10) / 10,
      km: Math.round(b.km * 10) / 10,
      avgHr: b.hrCount > 0 ? Math.round(b.hrSum / b.hrCount) : null
    }));
    const text = `Trailing ${weeks}-week rollup (${data.length} sessions, ${Math.round(totalHours * 10) / 10} h total, ${Math.round(totalHours / weeks * 10) / 10} h/week):
` + rows.map(
      (r) => `- ${r.discipline}: ${r.sessions} sessions | ${r.hours} h | ${r.km} km${r.avgHr ? ` | avg HR ${r.avgHr}` : ""}`
    ).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        weeks,
        totalSessions: data.length,
        totalHours: Math.round(totalHours * 10) / 10,
        hoursPerWeek: Math.round(totalHours / weeks * 10) / 10,
        disciplines: rows
      }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cdrpypapdqbwwiuqvqti";
var mcp_default = defineMcp({
  name: "hybrid-athletics-mcp",
  title: "Hybrid Athletics",
  version: "0.1.0",
  instructions: "Read-only access to the signed-in HYROX athlete's training data on Hybrid Athletics. Use `get_todays_session` for today's workout, `list_upcoming_sessions` to look ahead, `list_recent_completions` for recent training history, `get_training_load` for the current CTL/ATL/TSB fitness/fatigue snapshot, `get_goal_race` for the athlete's next HYROX race, `list_strava_activities` for activities synced from Strava, and `get_weekly_rollup` for a trailing per-discipline volume summary. All tools return data for the signed-in user only.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_todays_session_default,
    list_upcoming_sessions_default,
    list_recent_completions_default,
    get_training_load_default,
    get_goal_race_default,
    list_strava_activities_default,
    get_weekly_rollup_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
